GROUP_NAME = 'liveblog'
#IFANR_FEED_URL = 'http://www.ifanr.com/feed'
#IFANR_FEED_URL = 'http://feeds.bbci.co.uk/zhongwen/trad/rss.xml'
IFANR_FEED_URL = 'http://feeds.bbci.co.uk/news/world/rss.xml'
#IFANR_FEED_URL = 'http://www.bbc.com/news'
