# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbIndexTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockNO', models.CharField(max_length=20)),
                ('TradeDate', models.DateTimeField()),
                ('TickTime', models.DateTimeField()),
                ('P_Open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_High', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_Low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_Close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TradeQty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ave_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Red', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tbTradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockNO', models.CharField(max_length=20)),
                ('TradeDate', models.DateTimeField()),
                ('TickTime', models.DateTimeField()),
                ('BuyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SellPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TradePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Qty', models.DecimalField(decimal_places=0, max_digits=8)),
                ('AveP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BuyQty', models.DecimalField(decimal_places=0, max_digits=8)),
                ('SellQty', models.DecimalField(decimal_places=0, max_digits=8)),
                ('TickQty', models.DecimalField(decimal_places=0, max_digits=8)),
                ('AllQty', models.DecimalField(decimal_places=0, max_digits=8)),
                ('TickNO', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
